export const ROSTER = [
  'Kendrick Lamar',
  'Bad Bunny', 
  'Sombr',
  'Frank Ocean',
  'Juice WRLD',
  'XXXTENTACION',
  'Lil Peep',
  'Mac Miller',
  'Tame Impala',
  'Bjork',
  'Aphex Twin',
  'Tyler, The Creator',
  'Playboi Carti',
  'FKA Twigs',
  'Daft Punk',
  'The Weeknd',
  'Lana Del Rey',
  'Kanye West',
  'Radiohead',
  'Gorillaz',
  'Rosalia',
  'Travis Scott',
  'Lorde',
  'Drake',
  'J. Cole',
  'Billie Eilish',
  'SZA',
  'A$AP Rocky', 
  'Kid Cudi',
  'Post Malone'
];
